### PR TITLE
Make `BarLineChartViewBase.autoscale` method open

### PR DESCRIPTION
**Pull request by eirikvaa**
### Solution

Open up the `BarLineChartViewBase.autoScale` method so it can be overridden.

### Steps to Test or Reproduce
Clone the project (if you haven't already) and run the tests in the test target (`ChartsTests`).

### CODE REVIEW

**Comment by tkirshboim** [comment]
Are the changes to .pbxproj files necessary for this change to work?

**Comment by eirikvaa** [comment]
> Are the changes to .pbxproj files necessary for this change to work?

Nope! Habit from my side :-)

**Review by tkirshboim — APPROVED** [review]
LGTM.

**Review by LaStrada — APPROVED** [review]
🎉

**Pull request merged**
